image: openjdk:11

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ls -la .gradle/*
    - ./gradlew assemble

test:
  stage: test
  script:
   - ./gradlew check
  
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
